## Librerias

In [3]:
import pandas as pd
import numpy as np

## DFs

Tasa de suicidos

In [4]:
df_tasa = pd.read_csv("data\Tasa_suicidios\suicide-rate-who-mdb.csv")
df_tasa.rename(columns={
    "Age-standardized death rate from self-inflicted injuries per 100,000 population - Sex: Both sexes - Age group: all ages": "suicide_rate"
    }, inplace=True)
df_tasa

         Entity Code  Year  suicide_rate
0       Albania  ALB  1987      2.474300
1       Albania  ALB  1988      2.234553
2       Albania  ALB  1989      2.352273
3       Albania  ALB  1992      1.604659
4       Albania  ALB  1993      2.503264
...         ...  ...   ...           ...
4817  Venezuela  VEN  2012      2.629027
4818  Venezuela  VEN  2013      2.171715
4819  Venezuela  VEN  2014      1.994035
4820  Venezuela  VEN  2015      2.010758
4821  Venezuela  VEN  2016      2.942446

[4822 rows x 4 columns]

Numero de suicidos

In [13]:
df_num = pd.read_csv(r"data\Num_suicidios\number-of-deaths-from-suicide-ghe.csv")
df_num

           Entity Code  Year  Total deaths from self-harm among both sexes
0     Afghanistan  AFG  2000                                        858.50
1     Afghanistan  AFG  2001                                        870.15
2     Afghanistan  AFG  2002                                        900.94
3     Afghanistan  AFG  2003                                        967.23
4     Afghanistan  AFG  2004                                       1003.87
...           ...  ...   ...                                           ...
4417     Zimbabwe  ZWE  2017                                       2250.70
4418     Zimbabwe  ZWE  2018                                       2445.58
4419     Zimbabwe  ZWE  2019                                       2448.38
4420     Zimbabwe  ZWE  2020                                       2439.14
4421     Zimbabwe  ZWE  2021                                       2775.73

[4422 rows x 4 columns]

Pobreza extrema

In [6]:
df_pobre = pd.read_csv("data\pobreza_extrema\share-of-population-in-extreme-poverty.csv")
df_pobre

,Entity,Code,Year,Share of population in poverty ($3 a day),Population,World region according to OWID
0,Afghanistan,AFG,-10000,NaN,14737.0,Asia
1,Afghanistan,AFG,-9000,NaN,20405.0,Asia
2,Afghanistan,AFG,-8000,NaN,28253.0,Asia
3,Afghanistan,AFG,-7000,NaN,39120.0,Asia
4,Afghanistan,AFG,-6000,NaN,54166.0,Asia
...,...,...,...,...,...,...
59338,Zimbabwe,ZWE,2019,49.219894,15271377.0,Africa
59339,Zimbabwe,ZWE,2020,NaN,15526887.0,Africa
59340,Zimbabwe,ZWE,2021,NaN,15797220.0,Africa
59341,Zimbabwe,ZWE,2022,NaN,16069061.0,Africa
59342,Zimbabwe,ZWE,2023,NaN,16340829.0,Africa

Numero de psiquiatras

In [7]:
df_psquiatras = pd.read_csv("data\psiquiatras\psychiatrists-working-in-the-mental-health-sector.csv")
df_psquiatras

,Entity,Code,Year,"Total number of psychiatrists per 100,000 population"
0,Afghanistan,AFG,2019,0
1,Albania,ALB,2019,2
2,Algeria,DZA,2019,2
3,Andorra,AND,2019,10
4,Antigua and Barbuda,ATG,2019,1
...,...,...,...,...
138,Venezuela,VEN,2019,1
139,Vietnam,VNM,2019,1
140,Yemen,YEM,2019,0
141,Zambia,ZMB,2019,0
142,Zimbabwe,ZWE,2019,0

Num de suicidios por edades

In [8]:
df_j = pd.read_csv(r"data\num_suicidios_jovenes\suicide-rates-among-young-people-who-mdb.csv")
df_j

         Entity Code  Year  15–19 years  20–24 years  25–29 years
0       Albania  ALB  1987     2.899485     8.898015     2.432244
1       Albania  ALB  1988     1.578781     6.709158     1.702997
2       Albania  ALB  1989     1.557147     3.969567     5.038629
3       Albania  ALB  1992     3.073771     2.658564     1.927525
4       Albania  ALB  1993     4.595263     6.105006     4.125413
...         ...  ...   ...          ...          ...          ...
4782  Venezuela  VEN  2012     3.244654     3.576053     3.127036
4783  Venezuela  VEN  2013     2.208087     2.934232     2.949895
4784  Venezuela  VEN  2014     1.585020     2.380923     2.641347
4785  Venezuela  VEN  2015     1.892231     2.671919     2.048765
4786  Venezuela  VEN  2016     2.837793     3.699783     3.199509

[4787 rows x 6 columns]

Desempleo

In [9]:
df_des = pd.read_csv(r"data\Desempleo\unemployment-rate.csv")
df_des

           Entity Code  Year  Unemployment rate
0     Afghanistan  AFG  1991              7.972
1     Afghanistan  AFG  1992              7.958
2     Afghanistan  AFG  1993              7.908
3     Afghanistan  AFG  1994              7.883
4     Afghanistan  AFG  1995              7.868
...           ...  ...   ...                ...
6981     Zimbabwe  ZWE  2021              9.540
6982     Zimbabwe  ZWE  2022             10.087
6983     Zimbabwe  ZWE  2023              9.348
6984     Zimbabwe  ZWE  2024              9.435
6985     Zimbabwe  ZWE  2025              9.293

[6986 rows x 4 columns]

Alcoholismo

In [10]:
df_alco = pd.read_csv(r"data\Alcoholismo\total-alcohol-consumption-per-capita-litres-of-pure-alcohol.csv")
df_alco

           Entity Code  Year  Alcohol consumption
0     Afghanistan  AFG  2000                0.003
1     Afghanistan  AFG  2001                0.003
2     Afghanistan  AFG  2002                0.007
3     Afghanistan  AFG  2003                0.016
4     Afghanistan  AFG  2004                0.021
...           ...  ...   ...                  ...
4159     Zimbabwe  ZWE  2016                3.560
4160     Zimbabwe  ZWE  2017                3.520
4161     Zimbabwe  ZWE  2018                3.630
4162     Zimbabwe  ZWE  2019                3.630
4163     Zimbabwe  ZWE  2020                2.670

[4164 rows x 4 columns]

In [11]:
df_n = pd.read_csv(r"data\archive\age_std_suicide_rates_1990-2022.csv")
df_n

,RegionCode,RegionName,CountryCode,CountryName,Year,Sex,SuicideCount,CauseSpecificDeathPercentage,StdDeathRate,DeathRatePer100K,Population,GDP,GDPPerCapita,GNI,GNIPerCapita,InflationRate,EmploymentPopulationRatio
0,EU,Europe,ALB,Albania,1992,Male,33,0.331959,2.335802,2.076386,3247039.0,6.521750e+08,200.852220,9.061842e+08,1740.0,226.005421,45.315
1,EU,Europe,ALB,Albania,1992,Female,14,0.191860,0.866420,0.874563,3247039.0,6.521750e+08,200.852220,9.061842e+08,1740.0,226.005421,45.315
2,EU,Europe,ALB,Albania,1993,Male,46,0.477724,3.330938,2.937233,3227287.0,1.185315e+09,367.279225,1.024263e+09,2110.0,85.004751,47.798
3,EU,Europe,ALB,Albania,1993,Female,27,0.385164,1.755077,1.686025,3227287.0,1.185315e+09,367.279225,1.024263e+09,2110.0,85.004751,47.798
4,EU,Europe,ALB,Albania,1994,Male,37,0.419406,2.678796,2.332619,3207536.0,1.880951e+09,586.416135,1.216681e+09,2300.0,22.565053,50.086
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5923,AF,Africa,MYT,Mayotte,2015,Female,0,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5924,AF,Africa,REU,R?union,2016,Male,68,2.636681,15.399045,16.144005,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5925,AF,Africa,REU,R?union,2016,Female,17,0.796253,3.521507,3.790134,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5926,AF,Africa,REU,R?union,2015,Male,79,3.212688,18.702514,18.895318,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5927,AF,Africa,REU,R?union,2015,Female,20,0.965251,3.887067,4.491697,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df_n2 = pd.read_csv(r"data\archive\suicide_rates_1990-2022.csv")
df_n2.columns

Index(['RegionCode', 'RegionName', 'CountryCode', 'CountryName', 'Year', 'Sex',
       'AgeGroup', 'Generation', 'SuicideCount',
       'CauseSpecificDeathPercentage', 'DeathRatePer100K', 'Population', 'GDP',
       'GDPPerCapita', 'GrossNationalIncome', 'GNIPerCapita', 'InflationRate',
       'EmploymentPopulationRatio'],
      dtype='str')